/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelectRouteImport } from './routes/select'
import { Route as Activity56RouteImport } from './routes/activity56'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JourneyRouteIdRouteImport } from './routes/journey.$routeId'

const SelectRoute = SelectRouteImport.update({
  id: '/select',
  path: '/select',
  getParentRoute: () => rootRouteImport,
} as any)
const Activity56Route = Activity56RouteImport.update({
  id: '/activity56',
  path: '/activity56',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRouteIdRoute = JourneyRouteIdRouteImport.update({
  id: '/journey/$routeId',
  path: '/journey/$routeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity56': typeof Activity56Route
  '/select': typeof SelectRoute
  '/journey/$routeId': typeof JourneyRouteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity56': typeof Activity56Route
  '/select': typeof SelectRoute
  '/journey/$routeId': typeof JourneyRouteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity56': typeof Activity56Route
  '/select': typeof SelectRoute
  '/journey/$routeId': typeof JourneyRouteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/activity56' | '/select' | '/journey/$routeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/activity56' | '/select' | '/journey/$routeId'
  id: '__root__' | '/' | '/activity56' | '/select' | '/journey/$routeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Activity56Route: typeof Activity56Route
  SelectRoute: typeof SelectRoute
  JourneyRouteIdRoute: typeof JourneyRouteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/select': {
      id: '/select'
      path: '/select'
      fullPath: '/select'
      preLoaderRoute: typeof SelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity56': {
      id: '/activity56'
      path: '/activity56'
      fullPath: '/activity56'
      preLoaderRoute: typeof Activity56RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/$routeId': {
      id: '/journey/$routeId'
      path: '/journey/$routeId'
      fullPath: '/journey/$routeId'
      preLoaderRoute: typeof JourneyRouteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Activity56Route: Activity56Route,
  SelectRoute: SelectRoute,
  JourneyRouteIdRoute: JourneyRouteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
